RadixDesafioSensores/Models/EventoModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RadixDesafioSensores.Models
{
    public class EventoModel
    {
        [JsonProperty("timestamp")]
        public Int64 Timestamp { get; set; }

        [JsonProperty("valor")]
        public int Valor { get; set; }

        [JsonProperty("tag")]
        public string Tag { get; set; }

        public EventoModel(Int64 horario, string tag, int valor)
        {
            this.Timestamp = horario;
            this.Tag = tag;
            this.Valor = valor;
        }
    }
}

RadixDesafioSensores/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RadixDesafioSensores.Models;


namespace RadixDesafioSensores.Controllers
{
    public class EventosController : Controller
    {
        private static List<EventoModel> eventos = new List<EventoModel>();

        [HttpGet]
        public string Get()
        {
            HttpClient http = new HttpClient();
            //Existe uma pasta chamada 'API' na raiz do projeto onde é possível encontrar o código que gera os dados da API. 
            var data = http.GetAsync("https://randomapi.com/api/1b4050e14ab0a303bfd2eb5fd0cf5905").Result.Content.ReadAsStringAsync().Result;

            var eventoResult = JsonConvert.DeserializeObject<EventoModel>(data.Substring(0, data.IndexOf(']')).Substring(12));

            var resultado = new
            {
                timestamp = eventoResult.Timestamp,
                tag = eventoResult.Tag,
                valor = eventoResult.Valor
            };

            eventos.Add(new EventoModel(resultado.timestamp, resultado.tag, Convert.ToInt32(resultado.valor)));

            return data;
        }

        public IActionResult Index()
        {
            return View(eventos);
        }

        public IActionResult Sobre()
        {
            return View();
        }

        public string GerarDados()
        {
            List<string> regiao = new List<string>( new string[] { "sul", "sudeste", "norte", "nordeste" } );
            var sensor = new List<string>(new string[] { "sensor01", "sensor02" });
            var random = new Random();
            StringBuilder str = new StringBuilder();

            str.Append("brasil.");
            str.Append(regiao[random.Next(regiao.Count)]);
            str.Append("." + sensor[random.Next(sensor.Count)]);

            var resultado = new
            {
                timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds(),
                tag = Convert.ToString(str),
                valor = Convert.ToString(random.Next(0, 20))
            };

            eventos.Add(new EventoModel(resultado.timestamp, resultado.tag, Convert.ToInt32(resultado.valor)));
            System.Threading.Thread.Sleep(TimeSpan.FromSeconds(0.5));

            return JsonConvert.SerializeObject(resultado);
        }

        public void LimparDados()
        {
            eventos.Clear();
        }

        public string SudesteDados()
        {
            var sudeste = new
            {
                total = eventos.Where(x => x.Tag.Contains("sudeste")).Select(x => x.Valor > 0).Count(),
                sensor01 = eventos.Where(x => x.Tag.Contains("sudeste") && x.Tag.Contains("sensor01")).Select(x => x.Valor > 0).Count(),
                sensor02 = eventos.Where(x => x.Tag.Contains("sudeste") && x.Tag.Contains("sensor02")).Select(x => x.Valor > 0).Count()
            };
            return JsonConvert.SerializeObject(sudeste);
        }

        public string SulDados()
        {
            var sudeste = new
            {
                total = eventos.Where(x => x.Tag.Contains("sul")).Select(x => x.Valor > 0).Count(),
                sensor01 = eventos.Where(x => x.Tag.Contains("sul") && x.Tag.Contains("sensor01")).Select(x => x.Valor > 0).Count(),
                sensor02 = eventos.Where(x => x.Tag.Contains("sul") && x.Tag.Contains("sensor02")).Select(x => x.Valor > 0).Count()
            };
            return JsonConvert.SerializeObject(sudeste);
        }

        public string NorteDados()
        {
            var sudeste = new
            {
                total = eventos.Where(x => x.Tag.Contains("norte")).Select(x => x.Valor > 0).Count(),
                sensor01 = eventos.Where(x => x.Tag.Contains("norte") && x.Tag.Contains("sensor01")).Select(x => x.Valor > 0).Count(),
                sensor02 = eventos.Where(x => x.Tag.Contains("norte") && x.Tag.Contains("sensor02")).Select(x => x.Valor > 0).Count()
            };
            return JsonConvert.SerializeObject(sudeste);
        }

        public string NordesteDados()
        {
            var sudeste = new
            {
                total = eventos.Where(x => x.Tag.Contains("nordeste")).Select(x => x.Valor > 0).Count(),
                sensor01 = eventos.Where(x => x.Tag.Contains("nordeste") && x.Tag.Contains("sensor01")).Select(x => x.Valor > 0).Count(),
                sensor02 = eventos.Where(x => x.Tag.Contains("nordeste") && x.Tag.Contains("sensor02")).Select(x => x.Valor > 0).Count()
            };
            return JsonConvert.SerializeObject(sudeste);
        }
    }
}

RadixDesafioSensores/Views/Eventos/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
    <p>@ViewData["Message"]</p>
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Apuração de infrações por excesso de velocidade (BR)</h2>

<button class="btn btn-primary" id="buttonAPI">Consumir <b>API</b></button>

<button class="btn btn-info" id="buttonGerarDados">Gerar dados <b>localmente</b> </button>

<button class="btn btn-danger" id="buttonLimparDados">Limpar dados</button>

<div class="row">
    <div class="col-md-6">
        <table id="tabela_dados" class="tabela">
            <caption>Dados consumidos</caption>
            <thead>
                <tr>
                    <th>Horário da multa</th>
                    <th>Região</th>
                    <th>Multas registradas</th>
                    <th>Retorno do sensor</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var Model in Model)   
                    {
                        <tr class="@(Model.Valor == 0 ? "error-row" : "processado-row")">
                            <td>@Model.Timestamp</td>
                            <td>@Model.Tag.Split('.')[1]</td>
                            <td>@Model.Valor</td>
                            <td>@Model.Tag.Split('.')[2] : @(Model.Valor > 0 ? "Processado" : "Erro")</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <canvas id="bar-chart-grouped" width="800" height="450"></canvas>
        <canvas id="char-somatorio" width="800" height="450"></canvas>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">

        $("#buttonAPI").click(function () {
            for (var i = 0; i <= 15; i++) {
                $.getJSON("eventos/get", function (result) {

                    var corpoTabela = $('#tabela_dados').find("tbody");
                    var linha = '';

                    var classe = result.results[0].valor == 0 ? "error-row" : "processado-row";
                    var status = result.results[0].valor == 0 ? "Erro" : "Processado";

                    linha = '<tr class="' + classe + '"> ' +
                        '<td>' + time(result.results[0].timestamp) + '</td> ' +
                        '<td>' + result.results[0].tag.split('.')[1] + '</td>' +
                        '<td>' + result.results[0].valor + '</td> ' +
                        '<td>' + result.results[0].tag.split('.')[2] + ' : ' + status + ' </td> ' +
                        '</tr>';
                    corpoTabela.prepend(linha);

                    var ultima_linha = document.getElementById('tabela_dados').children[2].childElementCount;
                    if (ultima_linha > 15) {
                        document.getElementById('tabela_dados').deleteRow(ultima_linha)
                    };
                });
                setTimeout('', 1000);
            }
          //atualizarGrafico();
          //atualizarGraficoSomatorio(grafoSomatorio);
        });

        //--------------------.NET FUNÇÂO ---------------

        $("#buttonGerarDados").click(function () {
            for (var i = 0; i <= 20; i++) {
                $.getJSON("eventos/GerarDados", function (result) {

                    var corpoTabela = $('#tabela_dados').find("tbody");
                    var linhas = '';

                    var classe = result.valor == 0 ? "error-row" : "processado-row";
                    var status = result.valor == 0 ? "Erro" : "Processado";

                    linhas = '<tr class="' + classe + '"> ' +
                        '<td>' + time(result.timestamp) + '</td> ' +
                        '<td>' + result.tag.split('.')[1] + '</td>' +
                        '<td>' + result.valor + '</td> ' +
                        '<td>' + result.tag.split('.')[2] + ' : ' + status + ' </td> ' +
                        '</tr>';

                    corpoTabela.prepend(linhas);

                    var ultima_linha = document.getElementById('tabela_dados').children[2].childElementCount;
                    if (ultima_linha > 15) {
                        document.getElementById('tabela_dados').deleteRow(ultima_linha)
                    };

                });
                setTimeout('', 1000);
            }
          //atualizarGrafico();
          //atualizarGraficoSomatorio(grafoSomatorio);
        });

        //--------------Botão limpar dados-------------------

        $("#buttonLimparDados").click(function () {
            $.getJSON("eventos/LimparDados", void {});
            location.reload();
        });

        function time(s) {
            return new Date(s * 1e3).toISOString().slice(-13, -5);
        };

        function retornarSudeste() {
               var value= $.ajax({ 
                  url: 'eventos/SudesteDados', 
                   async: false
               }).responseText;
               return JSON.parse(value);
        };

        function retornarSul() {
               var value= $.ajax({ 
                  url: 'eventos/SulDados', 
                   async: false
               }).responseText;
               return JSON.parse(value);
        };

        function retornarNorte() {
               var value= $.ajax({ 
                  url: 'eventos/NorteDados', 
                   async: false
               }).responseText;
               return JSON.parse(value);
        };

        function retornarNordeste() {
               var value= $.ajax({ 
                  url: 'eventos/NordesteDados', 
                   async: false
               }).responseText;
               return JSON.parse(value);
        };

        var canvas = document.getElementById('bar-chart-grouped');
        var chart = new Chart(document.getElementById("bar-chart-grouped"), {
        type: 'bar',
        data: {
          labels: ["Norte", "Nordeste", "Sudeste", "Sul"],
          datasets: [
              {
              label: "Captadas pelo Sensor01",
              backgroundColor: "#3e95cd",
              data: [1, 1, 1, 1]
            }, {
              label: "Captadas pelo Sensor02",
              backgroundColor: "#8e5ea2",
              data: [1,1,1,1]
              },
          ]
        },
        options: {
                    scales: {
            yAxes: [{
                ticks: {
                    suggestedMin: 1,
                    suggestedMax: 15
                }
            }]
        },
          title: {
            display: true,
            text: 'Quantidade de infrações captadas por sensores'
          }
            }
        });

        function atualizarGrafico(chart, data, datasetIndex) {
            chart.data.datasets[0].data = [retornarNorte().sensor01, retornarNordeste().sensor01, retornarSudeste().sensor01, retornarSul().sensor01];
            chart.data.datasets[1].data = [retornarNorte().sensor02, retornarNordeste().sensor02, retornarSudeste().sensor02, retornarSul().sensor02];
            chart.update();
        }

      setInterval(function() {
          atualizarGrafico(chart);
          atualizarGraficoSomatorio(grafoSomatorio);
      }, 1500);




        //var grafo = document.getElementById('char-somatorio');
        var grafoSomatorio = new Chart(document.getElementById("char-somatorio"), {
        type: 'bar',
        data: {
          labels: ["Norte", "Nordeste", "Sudeste", "Sul"],
          datasets: [
              {
              label: "Somatório por região",
              backgroundColor: "#B2BABB",
              data: [1, 1, 1, 1]
            }
          ]
        },
        options: {
                    scales: {
            yAxes: [{
                ticks: {
                    suggestedMin: 1,
                    suggestedMax: 20
                }
            }]
        },
          title: {
            display: true,
            text: 'Somatório dos sensores lidos com sucesso'
          }
            }
        });

        function atualizarGraficoSomatorio(grafoSomatorio) {
            grafoSomatorio.data.datasets[0].data = [retornarNorte().total, retornarNordeste().total, retornarSudeste().total, retornarSul().total];
            grafoSomatorio.update();
        }

        
    </script>
}

RadixDesafioSensores/Views/Eventos/Sobre.cshtml
@{
    ViewData["Title"] = "Sobre";
}

<h2>Sobre</h2>


<h3>Como o sistema funciona?</h3>

<p>Olá! Me chamo Jonathan e estou no processo seletivo da RADIX! :)</p>
<p>
    O sistema irá consumir o número de ultrapassagens de velocidade no trânsito por segundo, captados por radares (sensores) de trânsitos nas regiões Sul, Sudeste, Norte e Nordeste.
</p>

<p>Os dados serão adicionados em uma tabela dinâmica, com os avisos se foram ou não processados. E, junto a isso, montar um gráfico que mostre a quantidade de multas feitas por dia em suas respectivas regiões (Sul, Sudeste, Norte e Nordeste).</p>

<p>O site foi desenvolvido para consumir uma WebAPI que retorna os dados pedidos para o desafio.</p>
<p>A criação da API foi feita no site: <a href="https://randomapi.com/">Random API</a>. Onde é possível escrever API's utilizando código Javascript (Código foi disponibilizado na pasta API, na raiz do projeto).</p>
<p>Pela limitação do RandomAPi ser de 500 chamadas diárias, criei um método no dot.net que retorna jsons para trabalhar com ele no front-end.</p>
<p>Ou seja, os dados podem ser gerados tanto pela API, quanto pelo .net.</p>



<p>Agradeço a Radix pela oportunidade! Foi uma experiência muito boa aprender a fazer um pequeno sistema desses. Aprendi muita coisa nova durante esses 5 dias e isso foi incrível!</p>

RadixDesafioSensores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Radix - Desafio com sensores</title>


    <environment include="Development">
        <link href="~/Content/Inicio.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>  
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Eventos" asp-action="Index" class="navbar-brand">Desafio Radix </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Eventos" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Eventos" asp-action="Sobre">Sobre</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; 2019 - Radix</p>
        </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>*@
        <script src="~/Content/Chart.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>